In [55]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [56]:
df = pd.read_csv("Churn_Modelling.csv")
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [57]:
df.drop(["RowNumber", "CustomerId", "Surname"], axis=1,inplace=True)
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [58]:
df.Gender.replace({"Female":1, "Male": 0}, inplace=True)
df.head()

C:\Users\adity\AppData\Local\Temp\ipykernel_12520\1172269515.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Gender.replace({"Female":1, "Male": 0}, inplace=True)
C:\Users\adity\AppData\Local\Temp\ipykernel_12520\1172269515.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.Gender.replace({"Female":1, "Male": 0}, inplace=True)

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,1,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,1,41,1,83807.86,1,0,1,112542.58,0
2,502,France,1,42,8,159660.80,3,1,0,113931.57,1
3,699,France,1,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,1,43,2,125510.82,1,1,1,79084.10,0

In [59]:
df.Geography.unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [60]:
geo = pd.get_dummies(df['Geography'],drop_first=True).astype(int)
df.drop(["Geography"], axis=1, inplace=True)
df = pd.concat([df,geo], axis=1)
df.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Germany,Spain
0,619,1,42,2,0.00,1,1,1,101348.88,1,0,0
1,608,1,41,1,83807.86,1,0,1,112542.58,0,0,1
2,502,1,42,8,159660.80,3,1,0,113931.57,1,0,0
3,699,1,39,1,0.00,2,0,0,93826.63,0,0,0
4,850,1,43,2,125510.82,1,1,1,79084.10,0,0,1

In [61]:
df.NumOfProducts.unique()

array([1, 3, 2, 4], dtype=int64)

In [62]:
cols_to_scale = ['CreditScore','Age','Tenure','Balance', 'NumOfProducts', 'EstimatedSalary']
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df[cols_to_scale] = scaler.fit_transform(df[cols_to_scale])

In [63]:
for col in df:
    print(f'{col}: {df[col].unique()}')
df.dtypes

CreditScore: [0.538 0.516 0.304 0.698 1.    0.59  0.944 0.052 0.302 0.668 0.356 0.294
 0.252 0.398 0.57  0.532 0.606 0.474 0.752 0.764 0.572 0.32  0.638 0.992
 0.454 0.812 0.442 0.448 0.122 0.482 0.366 0.406 0.34  0.744 0.25  0.28
 0.908 0.464 0.244 0.23  0.412 0.968 0.62  0.852 0.958 0.574 0.4   0.696
 0.47  0.876 0.61  0.502 0.612 0.75  0.322 0.528 0.784 0.674 0.41  0.506
 0.802 0.462 0.77  0.622 0.65  0.776 0.926 0.614 0.508 0.338 0.628 0.656
 0.814 0.132 0.63  0.854 0.386 0.312 0.286 0.604 0.8   0.758 0.592 0.594
 0.916 0.348 0.838 0.76  0.33  0.846 0.928 0.72  0.126 0.546 0.64  0.544
 0.87  0.51  0.258 0.67  0.376 0.424 0.742 0.556 0.636 0.956 0.648 0.55
 0.164 0.84  0.816 0.89  0.672 0.878 0.478 0.222 0.468 0.458 0.626 0.664
 0.886 0.682 0.27  0.6   0.808 0.37  0.732 0.378 0.712 0.472 0.562 0.734
 0.9   0.666 0.708 0.53  0.634 0.268 0.26  0.456 0.324 0.512 0.494 0.856
 0.328 0.35  0.73  0.46  0.914 0.342 0.818 0.332 0.722 0.536 0.586 0.642
 0.678 0.54  0.652 0.444 0.69  0.484 0.434 0.688 0.394 0.488 0.646 0.52
 0.834 0.826 0.724 0.706 0.624 0.618 0.346 0.844 0.39  0.568 0.778 0.842
 0.662 0.388 0.692 0.832 0.754 0.686 0.414 0.362 0.296 0.602 0.882 0.766
 0.922 0.714 0.728 0.864 0.85  0.898 0.504 0.788 0.476 0.794 0.466 0.554
 0.762 0.558 0.176 0.584 0.912 0.248 0.418 0.158 0.66  0.798 0.768 0.588
 0.552 0.598 0.91  0.736 0.98  0.56  0.608 0.824 0.436 0.526 0.344 0.774
 0.596 0.186 0.58  0.38  0.22  0.486 0.902 0.522 0.904 0.79  0.266 0.68
 0.284 0.718 0.71  0.42  0.804 0.702 0.374 0.274 0.492 0.704 0.272 0.748
 0.396 0.228 0.88  0.368 0.796 0.288 0.48  0.236 0.318 0.936 0.932 0.372
 0.806 0.848 0.542 0.438 0.616 0.896 0.582 0.384 0.684 0.578 0.83  0.44
 0.576 0.498 0.564 0.858 0.354 0.428 0.966 0.308 0.984 0.316 0.134 0.496
 0.782 0.514 0.822 0.996 0.392 0.178 0.81  0.82  0.352 0.726 0.7   0.632
 0.432 0.29  0.676 0.524 0.254 0.154 0.978 0.938 0.74  0.218 0.306 0.548
 0.358 0.426 0.264 0.892 0.19  0.792 0.872 0.408 0.644 0.874 0.298 0.988
 0.2   0.93  0.976 0.906 0.772 0.566 0.5   0.658 0.334 0.884 0.786 0.276
 0.142 0.982 0.716 0.314 0.31  0.212 0.17  0.422 0.336 0.43  0.756 0.868
 0.404 0.518 0.828 0.694 0.746 0.402 0.188 0.738 0.292 0.382 0.96  0.924
 0.654 0.14  0.49  0.534 0.918 0.3   0.952 0.168 0.326 0.256 0.894 0.026
 0.098 0.226 0.86  0.204 0.45  0.974 0.888 0.948 0.156 0.946 0.862 0.998
 0.278 0.162 0.214 0.836 0.962 0.018 0.94  0.446 0.452 0.416 0.934 0.198
 0.18  0.13  0.942 0.36  0.    0.192 0.15  0.78  0.262 0.866 0.016 0.99
 0.202 0.216 0.238 0.146 0.108 0.972 0.246 0.97  0.232 0.282 0.002 0.954
 0.986 0.03  0.364 0.128 0.206 0.242 0.102 0.92  0.964 0.24  0.194 0.144
 0.95  0.16  0.172 0.152 0.116 0.994 0.136 0.174 0.12  0.208 0.114 0.21
 0.224 0.072 0.11  0.066 0.09  0.234 0.166 0.184 0.148 0.196 0.182 0.034
 0.124 0.064 0.046 0.138]
Gender: [1 0]
Age: [0.32432432 0.31081081 0.28378378 0.33783784 0.35135135 0.43243243
 0.14864865 0.12162162 0.17567568 0.08108108 0.21621622 0.09459459
 0.22972973 0.36486486 0.54054054 0.18918919 0.27027027 0.37837838
 0.24324324 0.2027027  0.2972973  0.44594595 0.58108108 0.41891892
 0.25675676 0.01351351 0.64864865 0.51351351 0.10810811 0.04054054
 0.5        0.77027027 0.05405405 0.16216216 0.13513514 0.63513514
 0.40540541 0.45945946 0.52702703 0.74324324 0.39189189 0.48648649
 0.72972973 0.02702703 0.66216216 0.82432432 0.59459459 0.47297297
 0.83783784 0.55405405 0.67567568 0.06756757 0.56756757 0.7027027
 0.60810811 0.62162162 0.         0.86486486 0.68918919 0.75675676
 0.71621622 0.78378378 0.7972973  0.94594595 0.90540541 0.89189189
 0.81081081 0.85135135 1.         0.87837838]
Tenure: [0.2 0.1 0.8 0.7 0.4 0.6 0.3 1.  0.5 0.9 0. ]
Balance: [0.         0.33403148 0.63635718 ... 0.22865702 0.29922631 0.51870777]
NumOfProducts: [0.         0.66666667 0.33333333 1.        ]
HasCrCard: [1 0]
IsActiveMember: [1 0]
EstimatedSalary: [0.50673489 0.56270874 0.56965435 ... 0.21039009 0.46442905 0.19091423]
Exited: [1 0]
Germany: [0 1]
Spain: [0 1]

CreditScore        float64
Gender               int64
Age                float64
Tenure             float64
Balance            float64
NumOfProducts      float64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
Germany              int32
Spain                int32
dtype: object

In [64]:
y = df.Exited

In [65]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [66]:
X = df.drop("Exited", axis=1)

In [67]:
X

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Germany,Spain
0,0.538,1,0.324324,0.2,0.000000,0.000000,1,1,0.506735,0,0
1,0.516,1,0.310811,0.1,0.334031,0.000000,0,1,0.562709,0,1
2,0.304,1,0.324324,0.8,0.636357,0.666667,1,0,0.569654,0,0
3,0.698,1,0.283784,0.1,0.000000,0.333333,0,0,0.469120,0,0
4,1.000,1,0.337838,0.2,0.500246,0.000000,1,1,0.395400,0,1
...,...,...,...,...,...,...,...,...,...,...,...
9995,0.842,0,0.283784,0.5,0.000000,0.333333,1,0,0.481341,0,0
9996,0.332,0,0.229730,1.0,0.228657,0.000000,1,1,0.508490,0,0
9997,0.718,1,0.243243,0.7,0.000000,0.000000,0,1,0.210390,0,0
9998,0.844,0,0.324324,0.3,0.299226,0.333333,1,0,0.464429,1,0
9999,0.884,1,0.135135,0.4,0.518708,0.000000,1,0,0.190914,0,0

In [68]:
print(len(X))
print(len(X.columns))

10000
11

In [69]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train, y_test = train_test_split(X,y,test_size=0.2)

In [18]:
import tensorflow as tf
from tensorflow import keras
model = keras.Sequential([keras.layers.Dense(9,input_shape=(11,), activation='relu'),
                          keras.layers.Dense(6,activation='relu'),
                         keras.layers.Dense(1, activation='sigmoid')])
model.compile(optimizer='adam',
             loss='binary_crossentropy',
             metrics=['accuracy'])
model.fit(X_train,y_train,epochs=100)

Epoch 1/100
250/250 [==============================] - 3s 7ms/step - loss: 0.5544 - accuracy: 0.7881
Epoch 2/100
250/250 [==============================] - 2s 7ms/step - loss: 0.4981 - accuracy: 0.7979
Epoch 3/100
250/250 [==============================] - 2s 7ms/step - loss: 0.4795 - accuracy: 0.7979
Epoch 4/100
250/250 [==============================] - 2s 8ms/step - loss: 0.4625 - accuracy: 0.7986
Epoch 5/100
250/250 [==============================] - 2s 7ms/step - loss: 0.4495 - accuracy: 0.8037
Epoch 6/100
250/250 [==============================] - 2s 8ms/step - loss: 0.4391 - accuracy: 0.8100
Epoch 7/100
250/250 [==============================] - 2s 7ms/step - loss: 0.4324 - accuracy: 0.8144
Epoch 8/100
250/250 [==============================] - 2s 8ms/step - loss: 0.4268 - accuracy: 0.8188
Epoch 9/100
250/250 [==============================] - 2s 8ms/step - loss: 0.4240 - accuracy: 0.8177
Epoch 10/100
250/250 [==============================] - 2s 8ms/step - loss: 0.4217 - accuracy: 0.8194
Epoch 11/100
250/250 [==============================] - 2s 7ms/step - loss: 0.4204 - accuracy: 0.8199
Epoch 12/100
250/250 [==============================] - 2s 9ms/step - loss: 0.4178 - accuracy: 0.8192
Epoch 13/100
250/250 [==============================] - 2s 9ms/step - loss: 0.4153 - accuracy: 0.8227
Epoch 14/100
250/250 [==============================] - 2s 8ms/step - loss: 0.4089 - accuracy: 0.8280
Epoch 15/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3997 - accuracy: 0.8329
Epoch 16/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3889 - accuracy: 0.8374
Epoch 17/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3803 - accuracy: 0.8429
Epoch 18/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3735 - accuracy: 0.8461
Epoch 19/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3681 - accuracy: 0.8487
Epoch 20/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3651 - accuracy: 0.8491
Epoch 21/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3627 - accuracy: 0.8504
Epoch 22/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3614 - accuracy: 0.8499
Epoch 23/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3590 - accuracy: 0.8519
Epoch 24/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3585 - accuracy: 0.8505
Epoch 25/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3586 - accuracy: 0.8540
Epoch 26/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3564 - accuracy: 0.8540
Epoch 27/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3561 - accuracy: 0.8550
Epoch 28/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3562 - accuracy: 0.8541
Epoch 29/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3553 - accuracy: 0.8559
Epoch 30/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3538 - accuracy: 0.8554
Epoch 31/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3538 - accuracy: 0.8549
Epoch 32/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3534 - accuracy: 0.8565
Epoch 33/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3534 - accuracy: 0.8561
Epoch 34/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3521 - accuracy: 0.8577
Epoch 35/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3521 - accuracy: 0.8575
Epoch 36/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3511 - accuracy: 0.8565
Epoch 37/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3511 - accuracy: 0.8566
Epoch 38/100
250/250 [==============================] - 2s 10ms/step - loss: 0.3514 - accuracy: 0.8565
Epoch 39/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3506 - accuracy: 0.8574
Epoch 40/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3503 - accuracy: 0.8569
Epoch 41/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3502 - accuracy: 0.8561
Epoch 42/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3496 - accuracy: 0.8587
Epoch 43/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3500 - accuracy: 0.8568
Epoch 44/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3490 - accuracy: 0.8566
Epoch 45/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3496 - accuracy: 0.8576
Epoch 46/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3491 - accuracy: 0.8583
Epoch 47/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3484 - accuracy: 0.8587
Epoch 48/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3488 - accuracy: 0.8595
Epoch 49/100
250/250 [==============================] - 2s 10ms/step - loss: 0.3483 - accuracy: 0.8579
Epoch 50/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3484 - accuracy: 0.8590
Epoch 51/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3473 - accuracy: 0.8618
Epoch 52/100
250/250 [==============================] - 2s 10ms/step - loss: 0.3482 - accuracy: 0.8602
Epoch 53/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3472 - accuracy: 0.8581
Epoch 54/100
250/250 [==============================] - 2s 10ms/step - loss: 0.3472 - accuracy: 0.8608
Epoch 55/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3474 - accuracy: 0.8590
Epoch 56/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3475 - accuracy: 0.8597
Epoch 57/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3472 - accuracy: 0.8591
Epoch 58/100
250/250 [==============================] - 2s 10ms/step - loss: 0.3462 - accuracy: 0.8590
Epoch 59/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3464 - accuracy: 0.8600
Epoch 60/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3467 - accuracy: 0.8595
Epoch 61/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3461 - accuracy: 0.8595
Epoch 62/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3459 - accuracy: 0.8611
Epoch 63/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3465 - accuracy: 0.8602
Epoch 64/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3459 - accuracy: 0.8601
Epoch 65/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3461 - accuracy: 0.8596
Epoch 66/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3454 - accuracy: 0.8615
Epoch 67/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3455 - accuracy: 0.8597
Epoch 68/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3451 - accuracy: 0.8618
Epoch 69/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3454 - accuracy: 0.8604
Epoch 70/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3452 - accuracy: 0.8597
Epoch 71/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3446 - accuracy: 0.8599
Epoch 72/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3442 - accuracy: 0.8620
Epoch 73/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3449 - accuracy: 0.8593
Epoch 74/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3451 - accuracy: 0.8599
Epoch 75/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3445 - accuracy: 0.8605
Epoch 76/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3444 - accuracy: 0.8608
Epoch 77/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3446 - accuracy: 0.8608
Epoch 78/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3440 - accuracy: 0.8615
Epoch 79/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3439 - accuracy: 0.8612
Epoch 80/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3438 - accuracy: 0.8605
Epoch 81/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3446 - accuracy: 0.8620
Epoch 82/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3437 - accuracy: 0.8597
Epoch 83/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3438 - accuracy: 0.8600
Epoch 84/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3436 - accuracy: 0.8585
Epoch 85/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3436 - accuracy: 0.8612
Epoch 86/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3436 - accuracy: 0.8593
Epoch 87/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3438 - accuracy: 0.8622
Epoch 88/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3431 - accuracy: 0.8612
Epoch 89/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3436 - accuracy: 0.8615
Epoch 90/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3441 - accuracy: 0.8610
Epoch 91/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3430 - accuracy: 0.8604
Epoch 92/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3431 - accuracy: 0.8601
Epoch 93/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3426 - accuracy: 0.8624
Epoch 94/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3428 - accuracy: 0.8601
Epoch 95/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3429 - accuracy: 0.8625
Epoch 96/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3425 - accuracy: 0.8599
Epoch 97/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3426 - accuracy: 0.8614
Epoch 98/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3426 - accuracy: 0.8610
Epoch 99/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3418 - accuracy: 0.8615
Epoch 100/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3423 - accuracy: 0.8616

In [19]:
model.evaluate(X_test,y_test)

63/63 [==============================] - 1s 7ms/step - loss: 0.3434 - accuracy: 0.8580

[0.3433808386325836, 0.8579999804496765]

In [20]:
y_pred = model.predict(X_test)

63/63 [==============================] - 1s 5ms/step

In [21]:
y_pred[:10]

array([[0.10521767],
       [0.09290968],
       [0.00981737],
       [0.30128968],
       [0.05065428],
       [0.16399638],
       [0.18776694],
       [0.01163486],
       [0.50125164],
       [0.17743483]], dtype=float32)

In [22]:
y_test[:10]

6016    0
3468    0
2765    0
1107    1
1651    1
478     0
4735    0
4466    0
8961    0
1509    0
Name: Exited, dtype: int64

In [23]:
yp = []
for ele in y_pred:
    if ele > 0.5:
        yp.append(1)
    else:
        yp.append(0)

In [24]:
yp[:10]

[0, 0, 0, 0, 0, 0, 0, 0, 1, 0]

In [25]:
from sklearn.metrics import confusion_matrix, classification_report
print(classification_report(y_test, yp))

              precision    recall  f1-score   support

           0       0.87      0.97      0.92      1580
           1       0.79      0.44      0.57       420

    accuracy                           0.86      2000
   macro avg       0.83      0.70      0.74      2000
weighted avg       0.85      0.86      0.84      2000

In [26]:
confusion_matrix(y_test,yp)

array([[1531,   49],
       [ 235,  185]], dtype=int64)

In [47]:
#Below code is for undersampling, a technique used for skewed datasets.

In [70]:
class_0, class_1 = df.Exited.value_counts()

In [71]:
class_0, class_1

(7963, 2037)

In [72]:
df_class_0 = df[df.Exited == 0]
df_class_1 = df[df.Exited == 1]

In [73]:
df_under_class_0 = df_class_0.sample(class_1)
df_under_class_0.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Germany,Spain
3536,0.368,0,0.148649,0.7,0.696904,0.000000,1,1,0.395871,0,0,0
9244,0.392,1,0.094595,0.3,0.529449,0.000000,1,0,0.658242,0,1,0
958,0.362,0,0.121622,0.8,0.528407,0.000000,0,0,0.036060,0,0,1
7498,0.560,1,0.243243,0.8,0.504583,0.333333,1,1,0.672046,0,0,0
359,0.340,0,0.540541,0.3,0.000000,0.333333,0,1,0.163908,0,0,0

In [74]:
print(df_under_class_0.shape,df_class_1.shape)
df_class_1.head()

(2037, 12) (2037, 12)

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Germany,Spain
0,0.538,1,0.324324,0.2,0.000000,0.000000,1,1,0.506735,1,0,0
2,0.304,1,0.324324,0.8,0.636357,0.666667,1,0,0.569654,1,0,0
5,0.590,0,0.351351,0.8,0.453394,0.333333,1,0,0.748797,1,0,1
7,0.052,1,0.148649,0.4,0.458540,1.000000,1,0,0.596733,1,1,0
16,0.606,0,0.540541,0.1,0.528513,0.000000,1,0,0.025433,1,1,0

In [75]:
under_sampling_df = pd.concat([df_under_class_0,df_class_1], axis=0)

In [76]:
under_sampling_df.head()
under_sampling_df.shape

(4074, 12)

In [77]:
y = under_sampling_df.Exited
X = under_sampling_df.drop("Exited", axis=1)

In [78]:
X

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Germany,Spain
3536,0.368,0,0.148649,0.7,0.696904,0.000000,1,1,0.395871,0,0
9244,0.392,1,0.094595,0.3,0.529449,0.000000,1,0,0.658242,1,0
958,0.362,0,0.121622,0.8,0.528407,0.000000,0,0,0.036060,0,1
7498,0.560,1,0.243243,0.8,0.504583,0.333333,1,1,0.672046,0,0
359,0.340,0,0.540541,0.3,0.000000,0.333333,0,1,0.163908,0,0
...,...,...,...,...,...,...,...,...,...,...,...
9981,0.296,0,0.324324,0.3,0.605982,0.000000,1,1,0.267193,1,0
9982,0.610,1,0.378378,0.7,0.546617,0.000000,1,0,0.575729,1,0
9991,0.494,1,0.472973,0.4,0.352259,0.000000,1,0,0.346899,0,0
9997,0.718,1,0.243243,0.7,0.000000,0.000000,0,1,0.210390,0,0
9998,0.844,0,0.324324,0.3,0.299226,0.333333,1,0,0.464429,1,0

In [79]:
y

3536    0
9244    0
958     0
7498    0
359     0
       ..
9981    1
9982    1
9991    1
9997    1
9998    1
Name: Exited, Length: 4074, dtype: int64

In [80]:
X_train,X_test,y_train, y_test = train_test_split(X,y,test_size=0.2)

In [38]:
import tensorflow as tf
from tensorflow import keras
model = keras.Sequential([keras.layers.Dense(9,input_shape=(11,), activation='relu'),
                          keras.layers.Dense(6,activation='relu'),
                         keras.layers.Dense(1, activation='sigmoid')])
model.compile(optimizer='adam',
             loss='binary_crossentropy',
             metrics=['accuracy'])
model.fit(X_train,y_train,epochs=100)

Epoch 1/100
102/102 [==============================] - 2s 8ms/step - loss: 0.6986 - accuracy: 0.4529
Epoch 2/100
102/102 [==============================] - 1s 12ms/step - loss: 0.6729 - accuracy: 0.5851
Epoch 3/100
102/102 [==============================] - 1s 11ms/step - loss: 0.6574 - accuracy: 0.6223
Epoch 4/100
102/102 [==============================] - 1s 10ms/step - loss: 0.6454 - accuracy: 0.6352
Epoch 5/100
102/102 [==============================] - 1s 11ms/step - loss: 0.6348 - accuracy: 0.6484
Epoch 6/100
102/102 [==============================] - 1s 13ms/step - loss: 0.6264 - accuracy: 0.6563
Epoch 7/100
102/102 [==============================] - 1s 11ms/step - loss: 0.6200 - accuracy: 0.6625
Epoch 8/100
102/102 [==============================] - 1s 10ms/step - loss: 0.6136 - accuracy: 0.6708
Epoch 9/100
102/102 [==============================] - 1s 11ms/step - loss: 0.6068 - accuracy: 0.6769
Epoch 10/100
102/102 [==============================] - 1s 11ms/step - loss: 0.6017 - accuracy: 0.6775
Epoch 11/100
102/102 [==============================] - 1s 11ms/step - loss: 0.5970 - accuracy: 0.6873
Epoch 12/100
102/102 [==============================] - 1s 10ms/step - loss: 0.5919 - accuracy: 0.6925
Epoch 13/100
102/102 [==============================] - 1s 10ms/step - loss: 0.5871 - accuracy: 0.6950
Epoch 14/100
102/102 [==============================] - 1s 11ms/step - loss: 0.5819 - accuracy: 0.6993
Epoch 15/100
102/102 [==============================] - 1s 11ms/step - loss: 0.5801 - accuracy: 0.6968
Epoch 16/100
102/102 [==============================] - 1s 11ms/step - loss: 0.5768 - accuracy: 0.6993
Epoch 17/100
102/102 [==============================] - 1s 11ms/step - loss: 0.5732 - accuracy: 0.6996
Epoch 18/100
102/102 [==============================] - 1s 9ms/step - loss: 0.5733 - accuracy: 0.7005
Epoch 19/100
102/102 [==============================] - 1s 11ms/step - loss: 0.5666 - accuracy: 0.7057
Epoch 20/100
102/102 [==============================] - 1s 11ms/step - loss: 0.5615 - accuracy: 0.7094
Epoch 21/100
102/102 [==============================] - 1s 10ms/step - loss: 0.5521 - accuracy: 0.7162
Epoch 22/100
102/102 [==============================] - 1s 10ms/step - loss: 0.5415 - accuracy: 0.7288
Epoch 23/100
102/102 [==============================] - 1s 11ms/step - loss: 0.5340 - accuracy: 0.7324
Epoch 24/100
102/102 [==============================] - 1s 11ms/step - loss: 0.5252 - accuracy: 0.7370
Epoch 25/100
102/102 [==============================] - 1s 11ms/step - loss: 0.5181 - accuracy: 0.7465
Epoch 26/100
102/102 [==============================] - 1s 10ms/step - loss: 0.5116 - accuracy: 0.7524
Epoch 27/100
102/102 [==============================] - 1s 11ms/step - loss: 0.5068 - accuracy: 0.7512
Epoch 28/100
102/102 [==============================] - 1s 10ms/step - loss: 0.5004 - accuracy: 0.7597
Epoch 29/100
102/102 [==============================] - 1s 9ms/step - loss: 0.4962 - accuracy: 0.7585
Epoch 30/100
102/102 [==============================] - 1s 10ms/step - loss: 0.4934 - accuracy: 0.7600
Epoch 31/100
102/102 [==============================] - 1s 12ms/step - loss: 0.4905 - accuracy: 0.7561
Epoch 32/100
102/102 [==============================] - 1s 12ms/step - loss: 0.4876 - accuracy: 0.7647
Epoch 33/100
102/102 [==============================] - 1s 10ms/step - loss: 0.4851 - accuracy: 0.7625
Epoch 34/100
102/102 [==============================] - 1s 11ms/step - loss: 0.4828 - accuracy: 0.7656
Epoch 35/100
102/102 [==============================] - 1s 10ms/step - loss: 0.4830 - accuracy: 0.7665
Epoch 36/100
102/102 [==============================] - 1s 11ms/step - loss: 0.4804 - accuracy: 0.7699
Epoch 37/100
102/102 [==============================] - 1s 11ms/step - loss: 0.4797 - accuracy: 0.7640
Epoch 38/100
102/102 [==============================] - 1s 12ms/step - loss: 0.4784 - accuracy: 0.7674
Epoch 39/100
102/102 [==============================] - 1s 12ms/step - loss: 0.4770 - accuracy: 0.7720
Epoch 40/100
102/102 [==============================] - 1s 9ms/step - loss: 0.4766 - accuracy: 0.7693
Epoch 41/100
102/102 [==============================] - 1s 10ms/step - loss: 0.4751 - accuracy: 0.7689
Epoch 42/100
102/102 [==============================] - 1s 12ms/step - loss: 0.4744 - accuracy: 0.7708
Epoch 43/100
102/102 [==============================] - 1s 11ms/step - loss: 0.4746 - accuracy: 0.7680
Epoch 44/100
102/102 [==============================] - 1s 9ms/step - loss: 0.4752 - accuracy: 0.7723
Epoch 45/100
102/102 [==============================] - 1s 11ms/step - loss: 0.4726 - accuracy: 0.7702
Epoch 46/100
102/102 [==============================] - 1s 10ms/step - loss: 0.4729 - accuracy: 0.7693
Epoch 47/100
102/102 [==============================] - 1s 12ms/step - loss: 0.4730 - accuracy: 0.7714
Epoch 48/100
102/102 [==============================] - 1s 10ms/step - loss: 0.4732 - accuracy: 0.7736
Epoch 49/100
102/102 [==============================] - 1s 11ms/step - loss: 0.4713 - accuracy: 0.7705
Epoch 50/100
102/102 [==============================] - 1s 12ms/step - loss: 0.4704 - accuracy: 0.7732
Epoch 51/100
102/102 [==============================] - 1s 10ms/step - loss: 0.4703 - accuracy: 0.7745
Epoch 52/100
102/102 [==============================] - 1s 11ms/step - loss: 0.4692 - accuracy: 0.7726
Epoch 53/100
102/102 [==============================] - 1s 9ms/step - loss: 0.4707 - accuracy: 0.7696
Epoch 54/100
102/102 [==============================] - 1s 10ms/step - loss: 0.4700 - accuracy: 0.7763
Epoch 55/100
102/102 [==============================] - 1s 10ms/step - loss: 0.4705 - accuracy: 0.7739
Epoch 56/100
102/102 [==============================] - 1s 10ms/step - loss: 0.4697 - accuracy: 0.7757
Epoch 57/100
102/102 [==============================] - 1s 11ms/step - loss: 0.4686 - accuracy: 0.7760
Epoch 58/100
102/102 [==============================] - 1s 11ms/step - loss: 0.4688 - accuracy: 0.7754
Epoch 59/100
102/102 [==============================] - 1s 10ms/step - loss: 0.4698 - accuracy: 0.7717
Epoch 60/100
102/102 [==============================] - 1s 11ms/step - loss: 0.4681 - accuracy: 0.7723
Epoch 61/100
102/102 [==============================] - 1s 12ms/step - loss: 0.4689 - accuracy: 0.7769
Epoch 62/100
102/102 [==============================] - 1s 11ms/step - loss: 0.4695 - accuracy: 0.7717
Epoch 63/100
102/102 [==============================] - 1s 10ms/step - loss: 0.4672 - accuracy: 0.7772
Epoch 64/100
102/102 [==============================] - 1s 12ms/step - loss: 0.4671 - accuracy: 0.7696
Epoch 65/100
102/102 [==============================] - 1s 11ms/step - loss: 0.4671 - accuracy: 0.7769
Epoch 66/100
102/102 [==============================] - 1s 10ms/step - loss: 0.4670 - accuracy: 0.7782
Epoch 67/100
102/102 [==============================] - 1s 11ms/step - loss: 0.4682 - accuracy: 0.7775
Epoch 68/100
102/102 [==============================] - 1s 12ms/step - loss: 0.4662 - accuracy: 0.7788
Epoch 69/100
102/102 [==============================] - 1s 12ms/step - loss: 0.4679 - accuracy: 0.7751
Epoch 70/100
102/102 [==============================] - 1s 10ms/step - loss: 0.4676 - accuracy: 0.7754
Epoch 71/100
102/102 [==============================] - 1s 13ms/step - loss: 0.4663 - accuracy: 0.7732
Epoch 72/100
102/102 [==============================] - 1s 11ms/step - loss: 0.4664 - accuracy: 0.7726
Epoch 73/100
102/102 [==============================] - 1s 11ms/step - loss: 0.4673 - accuracy: 0.7757
Epoch 74/100
102/102 [==============================] - 1s 11ms/step - loss: 0.4658 - accuracy: 0.7751
Epoch 75/100
102/102 [==============================] - 1s 10ms/step - loss: 0.4654 - accuracy: 0.7757
Epoch 76/100
102/102 [==============================] - 1s 11ms/step - loss: 0.4658 - accuracy: 0.7742
Epoch 77/100
102/102 [==============================] - 1s 11ms/step - loss: 0.4652 - accuracy: 0.7760
Epoch 78/100
102/102 [==============================] - 1s 12ms/step - loss: 0.4647 - accuracy: 0.7766
Epoch 79/100
102/102 [==============================] - 1s 11ms/step - loss: 0.4648 - accuracy: 0.7739
Epoch 80/100
102/102 [==============================] - 1s 10ms/step - loss: 0.4650 - accuracy: 0.7782
Epoch 81/100
102/102 [==============================] - 1s 10ms/step - loss: 0.4645 - accuracy: 0.7729
Epoch 82/100
102/102 [==============================] - 1s 12ms/step - loss: 0.4648 - accuracy: 0.7818
Epoch 83/100
102/102 [==============================] - 1s 11ms/step - loss: 0.4649 - accuracy: 0.7797
Epoch 84/100
102/102 [==============================] - 1s 10ms/step - loss: 0.4647 - accuracy: 0.7754
Epoch 85/100
102/102 [==============================] - 1s 12ms/step - loss: 0.4649 - accuracy: 0.7757
Epoch 86/100
102/102 [==============================] - 1s 9ms/step - loss: 0.4647 - accuracy: 0.7766
Epoch 87/100
102/102 [==============================] - 1s 11ms/step - loss: 0.4658 - accuracy: 0.7720
Epoch 88/100
102/102 [==============================] - 1s 11ms/step - loss: 0.4636 - accuracy: 0.7757
Epoch 89/100
102/102 [==============================] - 1s 10ms/step - loss: 0.4650 - accuracy: 0.7772
Epoch 90/100
102/102 [==============================] - 1s 10ms/step - loss: 0.4647 - accuracy: 0.7800
Epoch 91/100
102/102 [==============================] - 1s 11ms/step - loss: 0.4641 - accuracy: 0.7760
Epoch 92/100
102/102 [==============================] - 1s 11ms/step - loss: 0.4639 - accuracy: 0.7788
Epoch 93/100
102/102 [==============================] - 1s 10ms/step - loss: 0.4629 - accuracy: 0.7736
Epoch 94/100
102/102 [==============================] - 1s 10ms/step - loss: 0.4631 - accuracy: 0.7785
Epoch 95/100
102/102 [==============================] - 1s 11ms/step - loss: 0.4634 - accuracy: 0.7782
Epoch 96/100
102/102 [==============================] - 1s 11ms/step - loss: 0.4629 - accuracy: 0.7757
Epoch 97/100
102/102 [==============================] - 1s 11ms/step - loss: 0.4636 - accuracy: 0.7745
Epoch 98/100
102/102 [==============================] - 1s 11ms/step - loss: 0.4630 - accuracy: 0.7788
Epoch 99/100
102/102 [==============================] - 1s 11ms/step - loss: 0.4628 - accuracy: 0.7791
Epoch 100/100
102/102 [==============================] - 1s 11ms/step - loss: 0.4626 - accuracy: 0.7778

In [39]:
model.evaluate(X_test,y_test)

26/26 [==============================] - 0s 7ms/step - loss: 0.4829 - accuracy: 0.7755

[0.48290181159973145, 0.7754601240158081]

In [40]:
y_pred = model.predict(X_test)

26/26 [==============================] - 0s 3ms/step

In [41]:
y_pred[:10]

array([[0.5361624 ],
       [0.09878465],
       [0.9389933 ],
       [0.16270377],
       [0.36822042],
       [0.12214842],
       [0.03675055],
       [0.5141882 ],
       [0.8563927 ],
       [0.38306755]], dtype=float32)

In [42]:
y_test[:10]

2381    1
2549    1
8603    1
5522    0
1652    0
7844    0
3394    0
5560    0
2501    0
7227    1
Name: Exited, dtype: int64

In [43]:
yp = []
for ele in y_pred:
    if ele > 0.5:
        yp.append(1)
    else:
        yp.append(0)

In [44]:
yp[:10]

[1, 0, 1, 0, 0, 0, 0, 1, 1, 0]

In [45]:
print(classification_report(y_test, yp))

              precision    recall  f1-score   support

           0       0.76      0.82      0.79       418
           1       0.79      0.73      0.76       397

    accuracy                           0.78       815
   macro avg       0.78      0.77      0.77       815
weighted avg       0.78      0.78      0.77       815

In [46]:
confusion_matrix(y_test,yp)

array([[342,  76],
       [107, 290]], dtype=int64)

In [48]:
#SMOTE code

In [81]:
from imblearn.over_sampling import SMOTE

In [82]:
smote = SMOTE(sampling_strategy='minority')

In [83]:
X = df.drop(['Exited'],axis='columns')
y = df['Exited']

In [84]:
X_smote, y_smote = smote.fit_resample(X,y)

In [86]:
y_smote.value_counts()

Exited
1    7963
0    7963
Name: count, dtype: int64

In [87]:
X_train,X_test,y_train,y_test = train_test_split(X_smote,y_smote,test_size=0.2,stratify=y_smote)

In [88]:
import tensorflow as tf
from tensorflow import keras
model = keras.Sequential([keras.layers.Dense(9,input_shape=(11,), activation='relu'),
                          keras.layers.Dense(6,activation='relu'),
                         keras.layers.Dense(1, activation='sigmoid')])
model.compile(optimizer='adam',
             loss='binary_crossentropy',
             metrics=['accuracy'])
model.fit(X_train,y_train,epochs=100)

Epoch 1/100
399/399 [==============================] - 5s 11ms/step - loss: 0.6754 - accuracy: 0.5800
Epoch 2/100
399/399 [==============================] - 5s 11ms/step - loss: 0.6346 - accuracy: 0.6425
Epoch 3/100
399/399 [==============================] - 5s 12ms/step - loss: 0.6008 - accuracy: 0.6786
Epoch 4/100
399/399 [==============================] - 5s 12ms/step - loss: 0.5736 - accuracy: 0.7041
Epoch 5/100
399/399 [==============================] - 4s 11ms/step - loss: 0.5597 - accuracy: 0.7158
Epoch 6/100
399/399 [==============================] - 4s 10ms/step - loss: 0.5522 - accuracy: 0.7206
Epoch 7/100
399/399 [==============================] - 4s 10ms/step - loss: 0.5419 - accuracy: 0.7261
Epoch 8/100
399/399 [==============================] - 4s 11ms/step - loss: 0.5149 - accuracy: 0.7475
Epoch 9/100
399/399 [==============================] - 4s 11ms/step - loss: 0.4945 - accuracy: 0.7571
Epoch 10/100
399/399 [==============================] - 4s 11ms/step - loss: 0.4822 - accuracy: 0.7613
Epoch 11/100
399/399 [==============================] - 4s 11ms/step - loss: 0.4735 - accuracy: 0.7672
Epoch 12/100
399/399 [==============================] - 4s 11ms/step - loss: 0.4677 - accuracy: 0.7705
Epoch 13/100
399/399 [==============================] - 4s 10ms/step - loss: 0.4637 - accuracy: 0.7706
Epoch 14/100
399/399 [==============================] - 4s 10ms/step - loss: 0.4596 - accuracy: 0.7731
Epoch 15/100
399/399 [==============================] - 4s 11ms/step - loss: 0.4572 - accuracy: 0.7768
Epoch 16/100
399/399 [==============================] - 4s 11ms/step - loss: 0.4549 - accuracy: 0.7768
Epoch 17/100
399/399 [==============================] - 4s 10ms/step - loss: 0.4528 - accuracy: 0.7788
Epoch 18/100
399/399 [==============================] - 4s 11ms/step - loss: 0.4510 - accuracy: 0.7794
Epoch 19/100
399/399 [==============================] - 4s 11ms/step - loss: 0.4497 - accuracy: 0.7813
Epoch 20/100
399/399 [==============================] - 4s 11ms/step - loss: 0.4483 - accuracy: 0.7834
Epoch 21/100
399/399 [==============================] - 4s 10ms/step - loss: 0.4470 - accuracy: 0.7830
Epoch 22/100
399/399 [==============================] - 4s 11ms/step - loss: 0.4456 - accuracy: 0.7849
Epoch 23/100
399/399 [==============================] - 4s 10ms/step - loss: 0.4444 - accuracy: 0.7852
Epoch 24/100
399/399 [==============================] - 4s 11ms/step - loss: 0.4427 - accuracy: 0.7867
Epoch 25/100
399/399 [==============================] - 4s 11ms/step - loss: 0.4421 - accuracy: 0.7869
Epoch 26/100
399/399 [==============================] - 5s 11ms/step - loss: 0.4411 - accuracy: 0.7888
Epoch 27/100
399/399 [==============================] - 4s 11ms/step - loss: 0.4404 - accuracy: 0.7900
Epoch 28/100
399/399 [==============================] - 4s 11ms/step - loss: 0.4391 - accuracy: 0.7893
Epoch 29/100
399/399 [==============================] - 4s 11ms/step - loss: 0.4373 - accuracy: 0.7929
Epoch 30/100
399/399 [==============================] - 4s 11ms/step - loss: 0.4365 - accuracy: 0.7922
Epoch 31/100
399/399 [==============================] - 4s 11ms/step - loss: 0.4355 - accuracy: 0.7961
Epoch 32/100
399/399 [==============================] - 4s 11ms/step - loss: 0.4357 - accuracy: 0.7930
Epoch 33/100
399/399 [==============================] - 5s 12ms/step - loss: 0.4340 - accuracy: 0.7919
Epoch 34/100
399/399 [==============================] - 4s 11ms/step - loss: 0.4331 - accuracy: 0.7958
Epoch 35/100
399/399 [==============================] - 4s 11ms/step - loss: 0.4328 - accuracy: 0.7951
Epoch 36/100
399/399 [==============================] - 5s 11ms/step - loss: 0.4315 - accuracy: 0.7939
Epoch 37/100
399/399 [==============================] - 4s 11ms/step - loss: 0.4320 - accuracy: 0.7965
Epoch 38/100
399/399 [==============================] - 4s 11ms/step - loss: 0.4315 - accuracy: 0.7958
Epoch 39/100
399/399 [==============================] - 4s 10ms/step - loss: 0.4303 - accuracy: 0.7958
Epoch 40/100
399/399 [==============================] - 4s 10ms/step - loss: 0.4299 - accuracy: 0.7987
Epoch 41/100
399/399 [==============================] - 4s 10ms/step - loss: 0.4281 - accuracy: 0.7974
Epoch 42/100
399/399 [==============================] - 4s 10ms/step - loss: 0.4292 - accuracy: 0.7975
Epoch 43/100
399/399 [==============================] - 4s 11ms/step - loss: 0.4290 - accuracy: 0.7965
Epoch 44/100
399/399 [==============================] - 4s 11ms/step - loss: 0.4282 - accuracy: 0.7970
Epoch 45/100
399/399 [==============================] - 5s 12ms/step - loss: 0.4265 - accuracy: 0.7986
Epoch 46/100
399/399 [==============================] - 4s 9ms/step - loss: 0.4279 - accuracy: 0.7973
Epoch 47/100
399/399 [==============================] - 4s 11ms/step - loss: 0.4272 - accuracy: 0.7979
Epoch 48/100
399/399 [==============================] - 4s 10ms/step - loss: 0.4260 - accuracy: 0.7973
Epoch 49/100
399/399 [==============================] - 5s 11ms/step - loss: 0.4260 - accuracy: 0.7969
Epoch 50/100
399/399 [==============================] - 5s 12ms/step - loss: 0.4255 - accuracy: 0.8006
Epoch 51/100
399/399 [==============================] - 4s 11ms/step - loss: 0.4250 - accuracy: 0.8014
Epoch 52/100
399/399 [==============================] - 4s 10ms/step - loss: 0.4253 - accuracy: 0.7999
Epoch 53/100
399/399 [==============================] - 4s 10ms/step - loss: 0.4255 - accuracy: 0.8007
Epoch 54/100
399/399 [==============================] - 4s 10ms/step - loss: 0.4233 - accuracy: 0.8016
Epoch 55/100
399/399 [==============================] - 4s 10ms/step - loss: 0.4253 - accuracy: 0.8020
Epoch 56/100
399/399 [==============================] - 4s 11ms/step - loss: 0.4233 - accuracy: 0.8016
Epoch 57/100
399/399 [==============================] - 5s 12ms/step - loss: 0.4234 - accuracy: 0.8010
Epoch 58/100
399/399 [==============================] - 4s 11ms/step - loss: 0.4226 - accuracy: 0.8005
Epoch 59/100
399/399 [==============================] - 4s 11ms/step - loss: 0.4231 - accuracy: 0.8026
Epoch 60/100
399/399 [==============================] - 4s 11ms/step - loss: 0.4216 - accuracy: 0.8024
Epoch 61/100
399/399 [==============================] - 5s 11ms/step - loss: 0.4216 - accuracy: 0.8034
Epoch 62/100
399/399 [==============================] - 5s 11ms/step - loss: 0.4234 - accuracy: 0.8015
Epoch 63/100
399/399 [==============================] - 4s 11ms/step - loss: 0.4225 - accuracy: 0.8009
Epoch 64/100
399/399 [==============================] - 5s 12ms/step - loss: 0.4221 - accuracy: 0.8017
Epoch 65/100
399/399 [==============================] - 5s 12ms/step - loss: 0.4215 - accuracy: 0.8020
Epoch 66/100
399/399 [==============================] - 4s 11ms/step - loss: 0.4212 - accuracy: 0.8016
Epoch 67/100
399/399 [==============================] - 5s 11ms/step - loss: 0.4212 - accuracy: 0.8010
Epoch 68/100
399/399 [==============================] - 5s 12ms/step - loss: 0.4198 - accuracy: 0.8042
Epoch 69/100
399/399 [==============================] - 5s 12ms/step - loss: 0.4203 - accuracy: 0.8002
Epoch 70/100
399/399 [==============================] - 5s 11ms/step - loss: 0.4203 - accuracy: 0.8038
Epoch 71/100
399/399 [==============================] - 3s 7ms/step - loss: 0.4199 - accuracy: 0.8033
Epoch 72/100
399/399 [==============================] - 2s 6ms/step - loss: 0.4199 - accuracy: 0.8014
Epoch 73/100
399/399 [==============================] - 2s 5ms/step - loss: 0.4190 - accuracy: 0.8038
Epoch 74/100
399/399 [==============================] - 2s 5ms/step - loss: 0.4194 - accuracy: 0.8021
Epoch 75/100
399/399 [==============================] - 2s 6ms/step - loss: 0.4185 - accuracy: 0.8057
Epoch 76/100
399/399 [==============================] - 2s 5ms/step - loss: 0.4185 - accuracy: 0.8045
Epoch 77/100
399/399 [==============================] - 2s 5ms/step - loss: 0.4185 - accuracy: 0.8035
Epoch 78/100
399/399 [==============================] - 2s 5ms/step - loss: 0.4188 - accuracy: 0.8042
Epoch 79/100
399/399 [==============================] - 2s 5ms/step - loss: 0.4179 - accuracy: 0.8038
Epoch 80/100
399/399 [==============================] - 2s 5ms/step - loss: 0.4185 - accuracy: 0.8035
Epoch 81/100
399/399 [==============================] - 2s 5ms/step - loss: 0.4171 - accuracy: 0.8029
Epoch 82/100
399/399 [==============================] - 2s 5ms/step - loss: 0.4177 - accuracy: 0.8046
Epoch 83/100
399/399 [==============================] - 2s 5ms/step - loss: 0.4181 - accuracy: 0.8053
Epoch 84/100
399/399 [==============================] - 2s 5ms/step - loss: 0.4182 - accuracy: 0.8043
Epoch 85/100
399/399 [==============================] - 2s 5ms/step - loss: 0.4178 - accuracy: 0.8036
Epoch 86/100
399/399 [==============================] - 2s 5ms/step - loss: 0.4171 - accuracy: 0.8028
Epoch 87/100
399/399 [==============================] - 2s 5ms/step - loss: 0.4171 - accuracy: 0.8052
Epoch 88/100
399/399 [==============================] - 2s 5ms/step - loss: 0.4165 - accuracy: 0.8048
Epoch 89/100
399/399 [==============================] - 2s 5ms/step - loss: 0.4165 - accuracy: 0.8055
Epoch 90/100
399/399 [==============================] - 2s 5ms/step - loss: 0.4160 - accuracy: 0.8081
Epoch 91/100
399/399 [==============================] - 2s 5ms/step - loss: 0.4154 - accuracy: 0.8040
Epoch 92/100
399/399 [==============================] - 2s 6ms/step - loss: 0.4170 - accuracy: 0.8051
Epoch 93/100
399/399 [==============================] - 2s 6ms/step - loss: 0.4163 - accuracy: 0.8067
Epoch 94/100
399/399 [==============================] - 2s 6ms/step - loss: 0.4165 - accuracy: 0.8057
Epoch 95/100
399/399 [==============================] - 2s 6ms/step - loss: 0.4154 - accuracy: 0.8079
Epoch 96/100
399/399 [==============================] - 2s 6ms/step - loss: 0.4156 - accuracy: 0.8059
Epoch 97/100
399/399 [==============================] - 2s 5ms/step - loss: 0.4155 - accuracy: 0.8058
Epoch 98/100
399/399 [==============================] - 2s 6ms/step - loss: 0.4155 - accuracy: 0.8056
Epoch 99/100
399/399 [==============================] - 2s 6ms/step - loss: 0.4152 - accuracy: 0.8065
Epoch 100/100
399/399 [==============================] - 2s 6ms/step - loss: 0.4139 - accuracy: 0.8060

In [89]:
model.evaluate(X_test,y_test)

100/100 [==============================] - 1s 5ms/step - loss: 0.4349 - accuracy: 0.7969

[0.43492749333381653, 0.7969240546226501]

In [90]:
y_pred = model.predict(X_test)

100/100 [==============================] - 0s 2ms/step

In [91]:
y_pred[:10]

array([[0.09073295],
       [0.8583711 ],
       [0.8826778 ],
       [0.8944669 ],
       [0.69319594],
       [0.4999615 ],
       [0.9573204 ],
       [0.09085844],
       [0.73264307],
       [0.9730112 ]], dtype=float32)

In [92]:
y_test[:10]

336      0
1057     1
9766     0
12331    1
12876    1
7463     0
15395    1
7761     0
8591     0
11128    1
Name: Exited, dtype: int64

In [93]:
yp = []
for ele in y_pred:
    if ele > 0.5:
        yp.append(1)
    else:
        yp.append(0)

In [94]:
yp[:10]

[0, 1, 1, 1, 1, 0, 1, 0, 1, 1]

In [95]:
print(classification_report(y_test, yp))

              precision    recall  f1-score   support

           0       0.81      0.78      0.79      1593
           1       0.79      0.81      0.80      1593

    accuracy                           0.80      3186
   macro avg       0.80      0.80      0.80      3186
weighted avg       0.80      0.80      0.80      3186

In [96]:
confusion_matrix(y_test,yp)

array([[1248,  345],
       [ 302, 1291]], dtype=int64)